# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b839538c029e3bdde5a2c0a65c268b035b9bbf197ede909954131a9d5db80b04db3b785fc1267381aab1279cebf7623339fd50b2085b951c79f9216faeaaf1f8

test:
  secret_key_base: c662b4b692a2216e338851c8f1ed4e8feb1cf33fc0c86c5a72ba50f61a700604e1a0695ea4a2286260fa1ec4a06613fdeccee49a700fe7c8efa8ea95c1d06bc5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
